name: Auto merge
on: pull_request
jobs:
    merge:                                                          # Dependabot 풀 리퀘스트만 대상
        if: ${{ github.actor == 'dependabot[bot]' }}
        runs-on: ubuntu-latest                                      
        permissions:                                                # 머지에 필요한 권한
            contents: write
            pull-requests: write
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}               # 깃허브 CLI 인증 정보
        steps:
            - uses: actions/checkout@v4
            - run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto         # 깃허브 CLI로 머지