name: Intermediate-environment-variables
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            ACTOR: ${{ github.actor }}
            RUN_ID: ${{ github.run_id }}
        steps: 
            - run: echo "${ACTOR} ${RUN_ID}"