name: Missing share data
on: push
jobs:
    share:
        runs-on: ubutu-latest
        steps:
            - run: export RESULT="Hello"        # 환경변수를 사용해 다음 스텝에 값을 전달하려고 한다.
            - run: echo "${RESULT}"             # 하지만 환경변수를 참조해도 값이 비어있다.